require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  TargetRubyVersion: 3.0
  Exclude:
    - bin/**/*
    - config/**/*
    - db/**/*
    - lib/tasks/*.rake
    - public/**/*
    - tmp/**/*
    - vendor/**/*

Documentation:
  Enabled: false

Metrics/BlockLength:
  ExcludedMethods: ['context', 'describe', 'feature', 'let', 'scenario']

Metrics/LineLength:
  Max: 130

Metrics/ClassLength:
  Enabled: false
