version: '3'

services:
  web:
    build: .
    container_name: pharma-inc-web
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
    volumes:
      - .:/home/rails/pharma-inc-api
    ports:
      - 3000:3000
    networks:
      - rails-network
    depends_on:
      - db
  db:
    image: postgres:latest
    container_name: pharma-inc-db
    tty: true
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - rails-docker-pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - rails-network
volumes:
  rails-docker-pgdata:
    external: true
networks:
  rails-network:
    driver: bridge
